import { apiClient } from '@/lib/api-client';
import { DASHBOARD_ENDPOINTS } from '@/lib/api-endpoints';
import type { ApiResponse } from '@/types/api';
import type { AnalyticsDashboardData } from '@/types/analytics.types';

// Mock data chuẩn mực cho phân hệ Analytics
const MOCK_ANALYTICS_DATA: AnalyticsDashboardData = {
    kpis: {
        pageviews: 384920,
        pageviewsChange: 14.8,
        uniqueUsers: 92410,
        uniqueUsersChange: 8.5,
        avgSessionDuration: '04m 32s',
        avgSessionDurationChange: 12.3,
        bounceRate: 38.4,
        bounceRateChange: -3.2,
        activeOnlineNow: 148,
    },
    trafficTrend: [
        { name: 'Thứ 2', pageviews: 42100, sessions: 28400, users: 18200 },
        { name: 'Thứ 3', pageviews: 48900, sessions: 32600, users: 21500 },
        { name: 'Thứ 4', pageviews: 56300, sessions: 38200, users: 24900 },
        { name: 'Thứ 5', pageviews: 61400, sessions: 41800, users: 27100 },
        { name: 'Thứ 6', pageviews: 68900, sessions: 46200, users: 30400 },
        { name: 'Thứ 7', pageviews: 54200, sessions: 35100, users: 22800 },
        { name: 'CN', pageviews: 53120, sessions: 34200, users: 21900 },
    ],
    acquisitionSources: [
        {
            name: 'Tìm kiếm tự nhiên (Organic Search)',
            visitors: 161666,
            percentage: 42.0,
            color: 'accent',
            colorHex: '#3b82f6',
            icon: 'solar:magnifer-linear',
        },
        {
            name: 'Truy cập trực tiếp (Direct URL)',
            visitors: 107777,
            percentage: 28.0,
            color: 'success',
            colorHex: '#10b981',
            icon: 'solar:link-circle-linear',
        },
        {
            name: 'Mạng xã hội (Social Media)',
            visitors: 57738,
            percentage: 15.0,
            color: 'warning',
            colorHex: '#f59e0b',
            icon: 'solar:share-circle-linear',
        },
        {
            name: 'Giới thiệu từ website khác (Referral)',
            visitors: 38492,
            percentage: 10.0,
            color: 'default',
            colorHex: '#8b5cf6',
            icon: 'solar:users-group-rounded-linear',
        },
        {
            name: 'Quảng cáo trả phí (Paid Campaigns)',
            visitors: 19247,
            percentage: 5.0,
            color: 'danger',
            colorHex: '#ec4899',
            icon: 'solar:target-linear',
        },
    ],
    funnelSteps: [
        {
            step: 'Bước 1',
            name: 'Khách ghé thăm trang chủ / Landing',
            count: 92410,
            conversion: 100,
            dropoff: 0,
            color: 'accent',
        },
        {
            step: 'Bước 2',
            name: 'Xem chi tiết sản phẩm / Báo giá',
            count: 51750,
            conversion: 56.0,
            dropoff: 44.0,
            color: 'accent',
        },
        {
            step: 'Bước 3',
            name: 'Tương tác dùng thử / Đăng ký form',
            count: 23100,
            conversion: 25.0,
            dropoff: 55.4,
            color: 'warning',
        },
        {
            step: 'Bước 4',
            name: 'Xác thực tài khoản / Điền hồ sơ',
            count: 11800,
            conversion: 12.8,
            dropoff: 48.9,
            color: 'warning',
        },
        {
            step: 'Bước 5',
            name: 'Chuyển đổi thành công (Đơn hàng / Giao dịch)',
            count: 3548,
            conversion: 3.84,
            dropoff: 69.9,
            color: 'success',
        },
    ],
    topPages: [
        {
            id: 'page-1',
            path: '/dashboard',
            title: 'Bảng điều khiển trung tâm',
            views: 124800,
            uniqueUsers: 64200,
            avgTime: '03:42',
            bounceRate: 28.4,
            trend: 'up',
            statusType: 'optimal',
            createdAt: '2026-01-01',
            updatedAt: '2026-10-01',
            status: 'active',
        },
        {
            id: 'page-2',
            path: '/sales/products',
            title: 'Danh mục sản phẩm & Dịch vụ',
            views: 89400,
            uniqueUsers: 48100,
            avgTime: '04:15',
            bounceRate: 34.1,
            trend: 'up',
            statusType: 'optimal',
            createdAt: '2026-01-01',
            updatedAt: '2026-10-01',
            status: 'active',
        },
        {
            id: 'page-3',
            path: '/accounting/vietqr',
            title: 'Cổng thanh toán VietQR Pro',
            views: 65200,
            uniqueUsers: 39500,
            avgTime: '02:50',
            bounceRate: 22.8,
            trend: 'up',
            statusType: 'optimal',
            createdAt: '2026-01-01',
            updatedAt: '2026-10-01',
            status: 'active',
        },
        {
            id: 'page-4',
            path: '/crm/customers',
            title: 'Hồ sơ khách hàng doanh nghiệp',
            views: 45100,
            uniqueUsers: 24700,
            avgTime: '05:12',
            bounceRate: 41.6,
            trend: 'down',
            statusType: 'good',
            createdAt: '2026-01-01',
            updatedAt: '2026-10-01',
            status: 'active',
        },
        {
            id: 'page-5',
            path: '/reports/finance',
            title: 'Báo cáo doanh thu & Dòng tiền',
            views: 38200,
            uniqueUsers: 19800,
            avgTime: '06:04',
            bounceRate: 46.2,
            trend: 'up',
            statusType: 'needs_work',
            createdAt: '2026-01-01',
            updatedAt: '2026-10-01',
            status: 'active',
        },
    ],
    locations: [
        {
            city: 'TP. Hồ Chí Minh',
            country: 'Việt Nam',
            sessions: 109200,
            percentage: 42.5,
            revenueAvg: '1.450.000 đ',
        },
        {
            city: 'Hà Nội',
            country: 'Việt Nam',
            sessions: 81700,
            percentage: 31.8,
            revenueAvg: '1.620.000 đ',
        },
        {
            city: 'Đà Nẵng',
            country: 'Việt Nam',
            sessions: 28700,
            percentage: 11.2,
            revenueAvg: '1.180.000 đ',
        },
        {
            city: 'Cần Thơ & Miền Tây',
            country: 'Việt Nam',
            sessions: 14400,
            percentage: 5.6,
            revenueAvg: '980.000 đ',
        },
        {
            city: 'Hải Phòng',
            country: 'Việt Nam',
            sessions: 11300,
            percentage: 4.4,
            revenueAvg: '1.250.000 đ',
        },
        {
            city: 'Quốc tế (US, JP, SG...)',
            country: 'Nước ngoài',
            sessions: 11600,
            percentage: 4.5,
            revenueAvg: '2.840.000 đ',
        },
    ],
};

export const AnalyticsService = {
    getAnalyticsData: async (period: string = '7d'): Promise<ApiResponse<AnalyticsDashboardData>> => {
        try {
            return await apiClient.get<AnalyticsDashboardData>(DASHBOARD_ENDPOINTS.ANALYTICS, {
                params: { period },
            });
        } catch {
            return {
                returnCode: 200,
                data: MOCK_ANALYTICS_DATA,
                message: 'Lấy dữ liệu dự phòng thành công',
                errors: [],
            };
        }
    },
};
