import { useMemo } from 'react';
import { useTranslation } from 'react-i18next';
import { Button, Chip } from '@heroui/react';
import { ArrowDownTrayIcon, DocumentTextIcon, FunnelIcon } from '@heroicons/react/24/outline';
import { Breadcrumb } from '@/components/layout';
import {
    PageHeader,
    Table,
    TableColumn,
    TableAction,
    useTableData,
    FetchParams,
    PagedResult,
} from '@/components/common';

interface Report {
    id: number;
    name: string;
    type: 'pdf' | 'excel' | 'csv';
    generatedBy: string;
    generatedAt: string;
    status: 'completed' | 'processing' | 'failed';
    size: string;
}

const mockReports: Report[] = Array.from({ length: 20 }, (_, i) => ({
    id: i + 1,
    name: `Monthly Sales Report - ${new Date(2024, i % 12, 1).toLocaleString('default', { month: 'long' })} 2024`,
    type: (['pdf', 'excel', 'csv'] as const)[i % 3],
    generatedBy: `User ${i + 1}`,
    generatedAt: new Date(2024, i % 12, i + 1).toISOString(),
    status: (['completed', 'completed', 'completed', 'processing', 'failed'] as const)[i % 5],
    size: `${(Math.random() * 5 + 1).toFixed(1)} MB`,
}));

const fetchReports = async (params: FetchParams): Promise<PagedResult<Report>> => {
    await new Promise((r) => setTimeout(r, 500)); // Simulate delay
    let filtered = [...mockReports];
    if (params.search) {
        const search = params.search.toLowerCase();
        filtered = filtered.filter((r) => r.name.toLowerCase().includes(search));
    }
    const start = (params.page - 1) * params.pageSize;
    const items = filtered.slice(start, start + params.pageSize);
    return {
        items,
        paging: {
            pageIndex: params.page,
            pageSize: params.pageSize,
            totalItems: filtered.length,
            totalPages: Math.ceil(filtered.length / params.pageSize),
        },
    };
};

export function DashboardReports() {
    const { t } = useTranslation();
    const {
        items,
        isLoading,
        total,
        page,
        pageSize,
        search,
        setPage,
        setPageSize,
        setSearch,
        refresh,
    } = useTableData<Report>({ fetchFn: fetchReports, initialPageSize: 10 });

    const getStatusColor = (status: string) => {
        switch (status) {
            case 'completed':
                return 'success';
            case 'processing':
                return 'warning';
            case 'failed':
                return 'danger';
            default:
                return 'default';
        }
    };

    const columns: TableColumn<Report>[] = useMemo(
        () => [
            {
                key: 'name',
                label: 'Report Name',
                render: (r) => (
                    <div className="flex items-center gap-2">
                        <DocumentTextIcon className="h-5 w-5 text-gray-400" />
                        <span className="font-medium text-gray-700 dark:text-gray-200">
                            {r.name}
                        </span>
                    </div>
                ),
            },
            {
                key: 'type',
                label: 'Type',
                width: 100,
                render: (r) => (
                    <Chip
                        size="sm"
                        variant="flat"
                        color={
                            r.type === 'pdf' ? 'danger' : r.type === 'excel' ? 'success' : 'primary'
                        }
                    >
                        {r.type.toUpperCase()}
                    </Chip>
                ),
            },
            {
                key: 'generatedAt',
                label: 'Date',
                render: (r) => new Date(r.generatedAt).toLocaleDateString(),
            },
            { key: 'generatedBy', label: 'Generated By' },
            { key: 'size', label: 'Size' },
            {
                key: 'status',
                label: 'Status',
                render: (r) => (
                    <Chip size="sm" variant="dot" color={getStatusColor(r.status)}>
                        {r.status.charAt(0).toUpperCase() + r.status.slice(1)}
                    </Chip>
                ),
            },
        ],
        []
    );

    const actions: TableAction<Report>[] = useMemo(
        () => [
            {
                key: 'download',
                label: 'Download',
                icon: <ArrowDownTrayIcon className="h-4 w-4" />,
                onClick: (r) => alert(`Downloading ${r.name}...`),
                isDisabled: (r) => r.status !== 'completed',
            },
        ],
        []
    );

    return (
        <>
            <Breadcrumb items={[{ label: t('menu.dashboard'), href: '#' }, { label: 'Reports' }]} />

            <PageHeader
                title="System Reports"
                description="View and download generated system reports."
                actions={
                    <Button
                        color="primary"
                        startContent={<FunnelIcon className="h-4 w-4" />}
                        radius="full"
                    >
                        Generate Report
                    </Button>
                }
            />

            <Table
                items={items}
                columns={columns}
                getRowKey={(r) => r.id}
                actions={actions}
                isLoading={isLoading}
                enableSkeleton={true}
                showSearch
                searchPlaceholder="Search reports..."
                searchValue={search}
                onSearchChange={setSearch}
                showRefresh
                onRefresh={refresh}
                pagination={{
                    page,
                    pageSize,
                    total,
                    onPageChange: setPage,
                    onPageSizeChange: setPageSize,
                }}
            />
        </>
    );
}
